config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)' do
    root 'store#index', as: :store
    get 'contact/index', as: :contact
    get 'news/index', as: :news
    get 'questions/index', as: :questions

    scope :admin do
      get "/", to: "admin#index", as: :admin
    end

    controller :sessions do
      get 'login', to: :new
      post 'login', to: :create
      delete 'logout', to: :destroy
    end


    resources :products do
      get :who_bought, on: :member
    end

    resources :users
    resources :orders
    resources :line_items
    resources :carts
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :delete_all

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)

    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def empty?
    line_items.empty?
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :order
  belongs_to :product
  def total_price
    quantity * product.price
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  PAYMENT_TYPES = [ "Check", "Credit Card", "Purchase Order" ]
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :orders, through: :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :price, :image_url, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }, if: 'price.present?'
  validates :image_url, allow_blank: true, format: {
    with: /\.(gif|jp[e]?g|png)\z/i,
    message: "Image url must be a URL for a .gif, .jpg, .jpeg or .png"
  }
  validates :title, uniqueness: true

  def self.latest
    Product.order(:updated_at).last
  end

  private

    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        true
      else
        errors.add(:base, "Line Item present")
      end
    end

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true

  has_secure_password

  after_destroy :admin_exists?

  private

    def admin_exists?
      raise "Cannot delete last administrator" if User.count.zero?
    end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  include CurrentCart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  skip_before_action :authorize, only: [:create, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        flash[:notice] = "Cart was successfully updated."
        format.html { redirect_to @cart }
        format.json { render :show, status: :ok, location: @cart }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil

    respond_to do |format|
      flash[:notice] = "Cart is currently empty."
      format.html { redirect_to store_path }
      format.json { head :no_content }
      format.js
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_path, notice: "Invalid Cart"
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def hidden_div_if(condition, attributes={}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag "div", attributes, &block
  end

  def notice_html_safe
    "<p>#{notice}</p>".html_safe if notice
  end

  def current_user
    User.find(session[:user_id])
  rescue ActiveRecord::RecordNotFound
    nil
  end

end

app/helpers/carts_helper.rb
module CartsHelper

  def has_cart?
    !@cart.nil?
  end

  def cart_empty?
    @cart.empty?
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome <%= current_user.name %></h1>

It's <%= Time.now %>, we have <%= pluralize @total_orders, "order" %>.

app/views/layouts/_admin_navigation.html.erb
<% if session[:user_id] %>
  <ul>
    <li><%= link_to "Store", store_path %></li>
    <li><%= link_to "Orders", orders_path %></li>
    <li><%= link_to "Products", products_path %></li>
    <li><%= link_to "Users", users_path %></li>
    <li>&nbsp;</li>
    <li><%= button_to "Logout", logout_path, method: :delete %></li>
  </ul>
<% end %>

app/views/layouts/_flash.html.erb
<%= hidden_div_if(notice.nil?, id: 'notice') do %>
  <%= notice_html_safe %>
<% end %>

app/views/layouts/_header.html.erb
<div id="banner">
  <%= link_to image_tag("logo.png"), session[:user_id].present? ? admin_path : store_path %>
  <%= @page_title || "Pragmatic Bookshelf" %>
</div>

app/views/layouts/_navigation.html.erb
<ul>
  <li><%= link_to "Questions", questions_path %></li>
  <li><%= link_to "News", news_path %></li>
  <li><%= link_to "Contact", contact_path %></li>
</ul>

app/views/layouts/_side_cart.html.erb
<% if has_cart? %>
  <%= hidden_div_if(cart_empty?, id: 'cart') do %>
    <%= render @cart %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>
<div id="columns">
  <div id="side">
    <%= render "layouts/navigation" %>
    <%= render "layouts/admin_navigation" %>
    <%= render "layouts/side_cart" %>
  </div>
  <div id="main">
    <%= render "layouts/flash" %>
    <%= yield %>
  </div>
</div>
<%= render "layouts/footer" %>

</body>
</html>

app/views/order_notifier/received.html.erb
<h3>Pragmatic Order Confirmation</h3>

<p>Dear <%= @order.name %></p>

<p>Thank you for your recent order from the Pragmatic Store.</p>

<p>You ordered the following items:</p>

<table>
  <thead>
    <tr>
      <th>Qty</th>
      <th>Description</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
    <%= render @order.line_items %>
  </tbody>
</table>

<p>We'll send you another email when your order ships.</p>

app/views/order_notifier/received.text.erb
Pragmatic Order Confirmation

Dear <%= @order.name %>,

Thank you for your recent order from the Pragmatic Store.

You ordered the following items:

<%= @order.line_items %>

We'll send you another email when your order ships.

app/views/order_notifier/shipped.html.erb
<h3>Pragmatic Order Shipped</h3>

<p>This is just to let you know that we've shipped your recent order:</p>

<table>
  <thead>
    <tr>
      <th>Qty</th>
      <th>Description</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
    <%= render @order.line_items %>
  </tbody>
</table>

app/views/order_notifier/shipped.text.erb
Pragmatic Order Shipped

Dear <%= @order.name %>,

This is just to let you know that we've shipped your recent order:

<%= @order.line_items %>